Bizom/Bizom/Controllers/CUSTOMEREXCELController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bizom.Models;
using Syncfusion.XlsIO;
using System.Data.Entity;
using System.Data;
using System.IO;

namespace Bizom.Controllers
{
    public class CUSTOMEREXCELController : Controller
    {
        DbBIZ obj = new DbBIZ();
        public ActionResult DOWNLOADEXCEL()
        {
            using (ExcelEngine excelengine = new ExcelEngine())
            {
                IApplication customer = excelengine.Excel;

                customer.DefaultVersion = ExcelVersion.Xlsx;

                IWorkbook workbook = customer.Workbooks.Create(1);

                IWorksheet worksheet = workbook.Worksheets[0];

                DataTable datatable = GETTABLE();
                worksheet.ImportDataTable(datatable, true, 1, 1);
                worksheet.UsedRange.AutofitColumns();

                workbook.SaveAs("CUSTOMER.xlsx", ExcelSaveType.SaveAsXLS, HttpContext.ApplicationInstance.Response, ExcelDownloadType.Open);
            }
            return View();
        }
        private DataTable GETTABLE()
        {
            DataTable table = new DataTable();
            table.Columns.Add("SELECT BEAT", typeof(string));
            table.Columns.Add("OUTLET TYPE", typeof(string));
            table.Columns.Add("OUTLET NAME", typeof(string));
            table.Columns.Add("OUTLET ADDRESS", typeof(string));
            table.Columns.Add("OWNER NAME", typeof(string));
            foreach (var item in obj.Retailers.ToList())
            {
                table.Rows.Add(@item.Select_Beat, @item.Outlet_Types, @item.Outlet_Name, @item.Outlet_Address, @item.Owner_Name);
            }
            return table;
        }
        [HttpPost]
        public ActionResult IMPORTEXCEL(HttpPostedFileBase customer)
        {
            string path = Path.GetFileName(customer.FileName);
            string rome = Path.Combine(Server.MapPath("~/EXCEL"), path);
            customer.SaveAs(rome);

            using(ExcelEngine excelengine = new ExcelEngine ())
            {
                IApplication application = excelengine.Excel;
                
                IWorkbook workbook = application.Workbooks.Open(rome);

                IWorksheet worksheet = workbook.Worksheets[0];
                var usedrange = worksheet.UsedRange;

                for (int row = 2; row <= usedrange.Rows.Length; row++)
                {
                    IRange BEAT = worksheet.Range[row, 1];
                    IRange OUTLET_TYPE = worksheet.Range[row, 2];
                    IRange OUTLET_NAME = worksheet.Range[row, 3];
                    IRange OUTLET_ADDRESS = worksheet.Range[row, 4];
                    IRange OWNER_NAME = worksheet.Range[row, 5];
                    var DATA = new Retailer
                    {
                        Select_Beat = BEAT.Text,
                        Outlet_Types = OUTLET_TYPE.Text,
                        Outlet_Name = OUTLET_NAME.Text,
                        Outlet_Address = OUTLET_ADDRESS.Text,
                        Owner_Name = OWNER_NAME.Text,
                    };
                    obj.Retailers.Add(DATA);
                    obj.SaveChanges();
                }
                return RedirectToAction("Read", "Read");
            }
        }
    }
}

Bizom/Bizom/Controllers/ReadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bizom.Models;
using PagedList;

namespace Bizom.Controllers
{
    [Authorize()]
    public class ReadController : Controller
    {

        DbBIZ obj = new DbBIZ();
        int PageSize = 10;
        int PageIndex = 1;
        public ActionResult Read(int ? page)
        {
            ViewBag.Co = obj.Retailers.Count();
            PageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            return View(obj.Retailers.OrderBy(m=>m.Retailer_Id).ToPagedList(PageIndex, PageSize));
        }
    }
}

Bizom/Bizom/Views/Read/Read.cshtml
@model PagedList.IPagedList<Bizom.Models.Retailer>
@using PagedList.Mvc;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>Read</title>
    <style>
        div {
            padding: 25px;
        }
    </style>
</head>
<body>
    <div>
        <a href="@Url.Action("DOWNLOADEXCEL", "CUSTOMEREXCEL")">DOWNLOAD</a>
        <br />
        @using (@Html.BeginForm("IMPORTEXCEL", "CUSTOMEREXCEL", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="customer" />
            <button>UPLOAD</button>
        }
    </div>
    <strong>No.of.Retailer</strong><span class="badge bg-danger">@ViewBag.Co</span>
    <div class="container w-75 ">
        <table class="table table-bordered table-striped text-center ">
            <tr>
                <th>RETAILER ID</th>
                <th>SELECT BEAT</th>
                <th>OUTLET TYPE</th>
                <th>OUTLET NAME</th>
                <th>OUTLET ADDRESS</th>
                <th>OWNER NAME</th>
                <th>OWNER NUMBER</th>
                <th>OUTLET IMAGE</th>
                <th>UPADATE/DELETE</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.Retailer_Id</th>
                    <th>@item.Select_Beat</th>
                    <th>@item.Outlet_Types</th>
                    <th>@item.Outlet_Name</th>
                    <th>@item.Outlet_Address</th>
                    <th>@item.Owner_Name</th>
                    <th>@item.Owner_Nunmer</th>
                    <th>
                        <img src="~/PRODUCT IMAGE/@item.Outlet_Image" width="100" height="100"/>
                    </th>
                    <th>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("Update", "Update", "Update", new { @id = item.Retailer_Id }, new{ @class = "btn btn-warning",
                            @onclick = "return confirm('are sure do UPDATE this record')"})
                            
                            @Html.ActionLink("Delete", "Delete", "Delete", new { @id = item.Retailer_Id }, new{ @class = "btn btn-warning",
                            @onclick = "return confirm('are sure do delete this record')"})
                        }
                        else if (User.Identity.IsAuthenticated && User.IsInRole("Staff"))
                        {
                            @Html.ActionLink("Update", "Update", "Update", new { @id = item.Retailer_Id }, new{ @class = "btn btn-warning",
                           @onclick = "return confirm('are sure do UPDATE this record')"})
                        }
                    </th>
                </tr>
            }
        </table>
    </div>
    <div class="page-item text-center">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Read", new { page }))

    </div>
</body>
</html>