Bizom/Bizom/Controllers/PRODUCTREADController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bizom.Models;

namespace Bizom.Controllers
{
    public class PRODUCTREADController : Controller
    {
        DbBIZ obj = new DbBIZ();
        public ActionResult PRODUCTREAD()
        {
            return View(obj.products.ToList());
        }
    }
}

Bizom/Bizom/Controllers/PRODUCT_EDIT_DELETEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using Bizom.Models;
using System.IO;

namespace Bizom.Controllers
{
    public class PRODUCT_EDIT_DELETEController : Controller
    {
        DbBIZ obj = new DbBIZ();
        public ActionResult PRODUCT_EDIT_DELETE(int id)
        {
            return View(obj.products.Find(id));
        }
        [HttpPost]
        public ActionResult PRODUCT_EDIT_DELETE(product R, HttpPostedFileBase PIC)
        {
            string path = Path.GetFileName(PIC.FileName);
            string P = Server.MapPath("~/PRODUCT IMAGE/" + path);
            PIC.SaveAs(P);
            R.PRODUCT_IMAGE = path;
            obj.Entry(R).State = EntityState.Modified;
            obj.SaveChanges();

            return RedirectToAction("PRODUCTREAD","PRODUCTREAD");
        }
        public ActionResult PRODUCT_DELETE(int id)
        {
            obj.products.Remove(obj.products.Find(id));
            obj.SaveChanges();
            return RedirectToAction("PRODUCTREAD", "PRODUCTREAD");
        }
    }
}

Bizom/Bizom/Views/PRODUCTREAD/PRODUCTREAD.cshtml
@model IEnumerable<Bizom.Models.product>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>PRODUCTREAD</title>
</head>
<body>
    <div>
        <a href="@Url.Action("DownloadExcel","Excel")">Download Excel</a>
    </div>
    <div>
        @using (@Html.BeginForm("ImportData", "Excel", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="king" />
            <button>Upload</button>
        }
    </div>
    <div>
        @Html.ActionLink("PRODUCT CREATION", "PRODUCTCREATION", "PRODUCTCREATION", FormMethod.Post, new { @class = "btn btn-info" })
    </div>
    <div class="container w-75">
        <table class="table table-bordered table-striped text-center  ">
            <tr>
                <th>PRODUCT ID</th>
                <th>BRAND</th>
                <th>SKU DESCRIPTION</th>
                <th>MRP</th>
                <th>MARGIN</th>
                <th>CASE QTY</th>
                <th>PRICE</th>
                <th>IMAGE</th>
                <th colspan="2">UPADATE/DELETE</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.product_id</th>
                    <th>@item.PRODUCT_BRAND</th>
                    <th>@item.PRODUCT_NAME</th>
                    <th>@item.PRODUCT_MAR</th>
                    <th>@item.PRODUCT_MARGIN</th>
                    <th>@item.PRODUCT_CASE</th>
                    <th>@item.PRODUCT_PRICE</th>
                    <th>
                        <img src="~/PRODUCT IMAGE/@item.PRODUCT_IMAGE" width="100" height="100" />
                    </th>
                    <th>
                        @Html.ActionLink("Update", "PRODUCT_EDIT_DELETE", "PRODUCT_EDIT_DELETE", new { @id = @item.product_id }, new { @class = "btn btn-warning" ,@onclick="return confirm('are sure UPDATE your record')" })
                        @Html.ActionLink("Delete", "PRODUCT_DELETE", "PRODUCT_EDIT_DELETE", new { @id = item.product_id }, new { @class = "btn btn-warning", @onclick = "return confirm('are sure DELETE your record')" })
                    </th>
                </tr>
            }
        </table>
    </div>
</body>
</html>