Bizom/Bizom/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bizom.Models;
using System.IO;
using System.Net.Mail;
using System.Net;

namespace Bizom.Controllers
{
    public class CreateController : Controller
    {
        
        DbBIZ obj = new DbBIZ();
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Retailer R,HttpPostedFileBase pic)
        {
            if (ModelState.IsValid)
            {
                string path = Path.GetFileName(pic.FileName);
                string name = Path.Combine(Server.MapPath("~/Image"), path);
                pic.SaveAs(name);
                R.Outlet_Image = path;
                obj.Retailers.Add(R);
                obj.SaveChanges();

                MailMessage message = new MailMessage();
                SmtpClient smtp = new SmtpClient();
                message.From = new MailAddress("ramdineshproject@gmail.com");
                message.To.Add(new MailAddress(R.EMAIL));
                message.Subject = "Account Creared!";
                message.IsBodyHtml = true;
                message.Body = "Account Created Successfully";
                smtp.Port = 587;
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("ramdineshproject@gmail.com", "tigw msfs ptxi qbbt");
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);


                TempData["MSG"] = "<script>alert('CREATED OUTLET')</script>";
                return RedirectToAction("Shop", "Shop");
                
            }
            else
            {
                return View();
            }

        }
      
    }
}

Bizom/Bizom/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bizom.Models;

namespace Bizom.Controllers
{
    public class ShopController : Controller
    {
        DbBIZ obj = new DbBIZ();
        public ActionResult Shop(string day)
        {
           
            if (day == "MONDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("BURMACOLONY")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("BURMACOLONY")).ToList());
            }
            else if (day == "TUESDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("KALANIVASAL")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("KALANIVASAL")).ToList());
            }
            else if (day == "WEDNESDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("SENJAI")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("SENJAI")).ToList());
            }
            else if (day == "THURSDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("RAILWAYROAD")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("RAILWAYROAD")).ToList());
            }
            else if (day == "FRIDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("PALLATHUR")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("PALLATHUR")).ToList());
            }
            else if (day == "SATURDAY")
            {
                ViewBag.co = obj.Retailers.Where(m => m.Select_Beat.Equals("PUTHUVAYAL")).Count();
                return View(obj.Retailers.Where(m => m.Select_Beat.Equals("PUTHUVAYAL")).ToList());
            }
            else
            {
                return View(obj.Retailers.ToList());
            }

        }
    }
}

Bizom/Bizom/Views/Shop/Shop.cshtml
@model IEnumerable<Bizom.Models.Retailer>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>Shop</title>
    <style>
        #BBB {
            position: relative;
            margin-bottom: 0px;
            text-align:center                 
        }

        #AAA {
            position: sticky;
            top: 0px;
            height:100px;
            z-index:2;
            
        }

        li {
            display: inline-block;
            margin: 25px;
        }
    </style>
</head>
<body>@Html.Raw(@TempData["MSG"])
    <div class="container " id="AAA" style="background-color:lightskyblue">
        <ul>
            <li>@Html.ActionLink("MONDAY", "Shop", "Shop", new { @day = "MONDAY" }, "")_(@ViewBag.co)</li>
            <li>@Html.ActionLink("TUESDAY", "Shop", "Shop", new { @day = "TUESDAY" }, "")_(@ViewBag.co)</li>
            <li>@Html.ActionLink("WEDNESDAY", "Shop", "Shop", new { @day = "WEDNESDAY" }, "")_(@ViewBag.co)</li>
            <li>@Html.ActionLink("THURSDAY", "Shop", "Shop", new { @day = "THURSDAY" }, "")_(@ViewBag.co)</li>
            <li>@Html.ActionLink("FRIDAY ", "Shop", "Shop", new { @day = "FRIDAY" }, "")_(@ViewBag.co)</li>
            <li>@Html.ActionLink("SATURDAY ", "Shop", "Shop", new { @day = "SATURDAY" }, "")_(@ViewBag.co)</li>

            <li>
               @Html.ActionLink("CREATE", "Create", "Create", "", new { @style = " btn btn-success; background-color:bisque; border-radius:50%;display:inline-block;width:60px;height:60px; text-align:center; color:black;" })
            </li>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li>
                    @Html.ActionLink("PRODUCT", "PRODUCTCREATION", "PRODUCTCREATION", "", new { @class = " btn btn-success" })
                </li>
            }
        </ul>
    </div>
    <div class="container w-50" id="BBB">

        @foreach (var item in Model)
        {
            <div class="container w-50 m-2 " style="background-color:bisque">
                
                <a href="@Url.Action("stock", "stock")">SHOP ID: @item.Retailer_Id</a>
                <br />
                <a href="@Url.Action("Stock", "Stock",item.Outlet_Name)">SHOP NAME :@item.Outlet_Name</a>
                <br />
                <img src="~/Image/@item.Outlet_Image" width="100" height="100" />
                <hr />
            </div>
        }
    </div>
</body>
</html>